name: Automated API tests using Postman CLI

on: push
schedule:
    - cron: "40 14 * * *"  

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "36401989-c0038753-29d1-437b-a1de-7b47d1797c24" -e "36401989-f9ca29b9-0a59-4892-bf10-899c3fecacb4"
